#
# Rules specified here take precedence over default Rubocop config
# Check the guide : https://github.com/rubocop-hq/ruby-style-guide
#

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'Guardfile'

Layout/LineLength:
  Description: 'Limit lines to X characters.'
  Enabled: true
  AutoCorrect: true
  Max: 160

Metrics/BlockLength:
  Description: 'Avoid long blocks with many lines.'
  Enabled: true
  CountComments: false
  ExcludedMethods:
    - refine
  Exclude:
    - 'spec/**/*'
