#
# Rules specified here take precedence over default Rubocop config
# Check the guide : https://github.com/rubocop-hq/ruby-style-guide
#

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'Guardfile'

################################################################################
################################## Layout ######################################
################################################################################

Layout/LineLength:
  Description: 'Limit lines to X characters.'
  Enabled: true
  AutoCorrect: true
  Max: 160

Layout/HashAlignment:
  Description: >-
                 Align the elements of a hash literal if they span more than
                 one line.
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Layout/BlockAlignment:
  Description: 'Align block ends correctly.'
  Enabled: true
  EnforcedStyleAlignWith: start_of_block

Layout/CaseIndentation:
  Description: 'Indentation of when in a case/when/[else/]end.'
  Enabled: true
  EnforcedStyle: end

Layout/ClassStructure:
  Description: 'Enforces a configured order of definitions within a class body.'
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - prepend
      - extend
    attribute_macros:
      - store_accessor
      - attr_accessor
      - attr_reader
      - attr_writer
    association:
      - belongs_to
      - has_one
      - has_and_belongs_to_many
      - has_many
    macros:
      - validates
      - validate
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_attribute_macros
      - association
      - public_delegate
      - macros
      - public_class_methods
      - initializer
      - public_methods
      - protected_attribute_macros
      - protected_methods
      - private_attribute_macros
      - private_delegate
      - private_methods

Layout/FirstArrayElementLineBreak:
  Description: >-
                 Checks for a line break before the first element in a
                 multi-line array.
  Enabled: true

Layout/FirstHashElementLineBreak:
  Description: >-
                 Checks for a line break before the first element in a
                 multi-line hash.
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Description: >-
                 Checks for a line break before the first argument in a
                 multi-line method call.
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Description: >-
                 Checks for a line break before the first parameter in a
                 multi-line method parameter definition.
  Enabled: true

################################################################################
################################## Naming ######################################
################################################################################

Naming/BlockParameterName:
  Description: >-
                Checks for block parameter names that contain capital letters,
                end in numbers, or do not meet a minimal length.
  Enabled: true
  VersionAdded: '0.53'
  # Parameter names may be equal to or greater than this value
  MinNameLength: 3
  # # Whitelisted names that will not register an offense
  AllowedNames:
    - id
  # Blacklisted names that will register an offense
  ForbiddenNames: []

Naming/VariableNumber:
  Description: >-
    Allow both normalcase and snake_case format for variable name with integer
  Enabled: false

################################################################################
################################## Style #######################################
################################################################################
Style/ClassAndModuleChildren:
  Description: 'This cop checks the style of children definitions at classes and modules'
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/SymbolArray:
  Description: 'Use arrays of symbols.'
  EnforcedStyle: brackets
  Enabled: true

Style/WordArray:
  Description: 'Use arrays of words.'
  StyleGuide: '#percent-w'
  Enabled: true
  EnforcedStyle: brackets

Style/RescueStandardError:
  Description: 'Avoid rescuing without specifying an error class.'
  Enabled: true
  EnforcedStyle: explicit

Style/HashEachMethods:
  Description: 'Use Hash#each_key and Hash#each_value.'
  StyleGuide: '#hash-each'
  Enabled: true
  VersionAdded: '0.80'
  Safe: false

Style/HashTransformKeys:
  Description: 'Prefer `transform_keys` over `each_with_object` and `map`.'
  Enabled: true
  Safe: false

Style/HashTransformValues:
  Description: 'Prefer `transform_values` over `each_with_object` and `map`.'
  Enabled: true
  Safe: false

################################################################################
################################## Rspec #######################################
################################################################################

RSpec/DescribedClass:
  Enabled: false

RSpec/MessageExpectation:
  Description: Checks for consistent message expectation style.
  Enabled: true
  EnforcedStyle: allow

RSpec/MultipleExpectations:
  Enabled: true

RSpec/ExampleLength:
  Enabled: true
  Max: 8

RSpec/EmptyLineAfterExample:
  Enabled: false
